name: Deploy Infrastructure and Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Initialize Backend Resources
        working-directory: terraform/backend
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Initialize and Deploy Infrastructure
        working-directory: terraform/infrastructure
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan

      - name: Package Lambda Function
        run: |
          zip lambda_function.zip lambda_function.py

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name merge-homeless-data \
            --zip-file fileb://lambda_function.zip

      - name: Upload Dataset Files to S3
        run: |
          aws s3 cp files/SF_HOMELESS_ANXIETY.csv s3://my-unique-datasets-bucket/raw/
          aws s3 cp files/SF_HOMELESS_DEMOGRAPHICS.csv s3://my-unique-datasets-bucket/raw/
